# Welcome to Jekyll!

# Basic Site Settings
locale                  : "en-US"
site_theme              : "default"
title                   : "Jitender Kumar / Academic Portfolio"
title_separator         : "-"
name                    : &name "Jitender Kumar"
description             : &description "Jitender Kumar's Computational Neuroscience Research Portfolio"
url                     : "https://jitenderk304.github.io" # Replace 'your-username' with your actual GitHub username
baseurl                 : "/Dr_Jitender_Kumar.github.io"
repository              : "Dr_jitender_kumar/your-username.github.io" # Replace 'your-username' with your actual GitHub username

# Site Author Settings
author:
  # Biographic information
  avatar                : "profile.png" # You can add your picture to /images/ profile.png later
  name                  : "Jitender Kumar"
  pronouns              :
  bio                   : "Computational Neuroscience Researcher"
  location              : "Calgary, AB, Canada"
  employer              : ""
  uri                   :
  email                 : "" 

  # Academic websites (Fill in URLs when you have them)
  academia              :
  arxiv                 :
  googlescholar         : "https://scholar.google.com/citations?user=2G4byuIAAAAJ&hl=en"
  inspire-hep          :
  impactstory           :
  orcid                 :
  semantic              :
  ssrn                  :
  pubmed                :
  researchgate          :
  scopus                :
  zotero                :

  # Repositories and software development
  bitbucket             :
  codepen               :
  dribbble              :
  github                : "Dr_jitender_kumar" # Replace with your GitHub username
  kaggle                :
  stackoverflow         :

  # Social media
  linkedin              : "https://www.linkedin.com/in/jkumar304/" # Put your LinkedIn profile link or username here
  twitter               : ""

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                  :
breadcrumbs             : false
words_per_minute        : 160
future                  : true
read_more               : "disabled"
talkmap_link            : false

# SEO Related
google_site_verification :
bing_site_verification   :

# Social Sharing
twitter:
  username              : &twitter
facebook:
  username              :
og_image                :
og_description          :

# Analytics
analytics:
  provider              : "false"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
